// Code generated by goctl. DO NOT EDIT!
// Source: austin.proto

package server

import (
	"context"

	"austin-go/app/austin-web/rpc/austin"
	"austin-go/app/austin-web/rpc/internal/logic"
	"austin-go/app/austin-web/rpc/internal/svc"
)

type AustinServer struct {
	svcCtx *svc.ServiceContext
	austin.UnimplementedAustinServer
}

func NewAustinServer(svcCtx *svc.ServiceContext) *AustinServer {
	return &AustinServer{
		svcCtx: svcCtx,
	}
}

func (s *AustinServer) Send(ctx context.Context, in *austin.SendRequest) (*austin.SendResponse, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}

func (s *AustinServer) BatchSend(ctx context.Context, in *austin.BatchSendRequest) (*austin.SendResponse, error) {
	l := logic.NewBatchSendLogic(ctx, s.svcCtx)
	return l.BatchSend(in)
}
