// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	commonversion "austin-go/app/austin-admin/api/internal/handler/common/version"
	send_account "austin-go/app/austin-admin/api/internal/handler/send_account"
	umslogin "austin-go/app/austin-admin/api/internal/handler/ums/login"
	"austin-go/app/austin-admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: umslogin.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/ver",
					Handler: commonversion.VersionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/demo"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/send_account/add",
				Handler: send_account.SendAccountAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send_account/edit",
				Handler: send_account.SendAccountEditHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/send_account/list",
				Handler: send_account.SendAccountListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
