// Code generated by goctl. DO NOT EDIT.
package types

type Page struct {
	Current   int    `form:"page,optional"`
	PageSize  int    `form:"pageSize,optional"`
	SortField string `form:"sort_field,optional"`
	Order     string `form:"order,optional"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"userInfo"`
}

type UserInfo struct {
	UserID    int64    `json:"userId,string"`
	UserName  string   `json:"userName"`
	Dashboard string   `json:"dashboard"`
	Role      []string `json:"role"`
}

type VersionResp struct {
	Version string `json:"version"`
}

type SendAccountAddReq struct {
	Title       string `json:"title"`
	Config      string `json:"config"`
	SendChannel int    `json:"send_channel"`
}

type SendAccountEditReq struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Config      string `json:"config"`
	SendChannel int    `json:"send_channel"`
}

type SendAccountItem struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Config      string `json:"config"`
	SendChannel int    `json:"send_channel"`
}

type SendAccountListReq struct {
	Title       string `form:"title,optional"`
	SendChannel string `form:"send_channel,optional"`
}

type SendAccountListResp struct {
	Items []SendAccountItem `json:"items"`
}
